[package]
name = "kornia-wgpu"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "WGPU backend for kornia-rs"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
include = { workspace = true }

[[example]]
name = "image_ops"
path = "examples/image_ops.rs"

[[example]]
name = "tensor_ops"
path = "examples/tensor_ops.rs"

[[example]]
name = "pipeline"
path = "examples/pipeline.rs"

[[example]]
name = "video_pipeline"
path = "examples/video_pipeline.rs"

[[bench]]
harness = false
name = "bench_resize"

[[bench]]
harness = false
name = "bench_tensor_ops"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
half = { version = "2", features = ["bytemuck"], optional = true }
kornia-image = { workspace = true }
kornia-imgproc = { workspace = true }
kornia-io = { workspace = true, features = ["gstreamer"] }
kornia-tensor = { workspace = true }
naga = { version = "28", optional = true }
pollster = "0.3"
thiserror = { workspace = true }
wgpu = { version = "28", features = ["wgsl"] }
gstreamer = "0.22"
gstreamer-app = "0.22"

[dev-dependencies]
criterion = { workspace = true }
kornia-io = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []
naga-validation = ["dep:naga"]
profiling = []
